- name: Check if NetworkManager is installed
  shell: 'ls /etc/NetworkManager/NetworkManager.conf'
  register: nm
  ignore_errors: True
  changed_when: False
- name: Disable DNSMasq for Torchpoint's Consul to work
  lineinfile: dest=/etc/NetworkManager/NetworkManager.conf line="#dns=dnsmasq" regexp="^#?dns=dnsmasq$"
  when: nm|success
